# -*- coding: utf-8 -*-
"""Fake account detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ezgcx4qMNqM--MaOnxFzsfyYK_HI1R--
"""

import cv2
from google.colab.patches import cv2_imshow
from google.colab import files
import numpy as np

# Load model
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Upload multiple images
uploaded = files.upload()

for file_name in uploaded.keys():
    print("\nProcessing:", file_name)

    img = cv2.imread(file_name)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    face_count = len(faces)
    image_area = img.shape[0] * img.shape[1]

    suspicious = False
    reason = []

    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0), 2)

        face_area = w * h
        ratio = face_area / image_area

        if ratio < 0.05:
            suspicious = True
            reason.append("Face too small")

    # Decision
    if face_count == 0:
        result = "Fake/Suspicious"
        reason.append("No face detected")
    elif face_count > 1:
        result = "Fake/Suspicious"
        reason.append("Multiple faces detected")
    elif suspicious:
        result = "Suspicious"
    else:
        result = "Likely Real"

    confidence = min(100, 50 + face_count*20)

    # Output
    print("Faces Detected:", face_count)
    print("Result:", result)
    print("Confidence:", confidence, "%")

    if reason:
        print("Reason:")
        for r in reason:
            print("-", r)

    cv2_imshow(img)